remote_file(
    name = "nvidia-cudnn-download",
    url = "https://files.pythonhosted.org/packages/77/f0/8236c886a061d203e51247aec2b8e3a8f5350178251ab57237daf2140680/nvidia_cudnn_cu12-9.8.0.87-py3-none-manylinux_2_27_x86_64.whl",
    sha256 = "d6b02cd0e3e24aa31d0193a8c39fec239354360d7d81055edddb69f35d53a4c8",
)

prebuilt_python_library(
    name = "nvidia-cudnn",
    binary_src = ":nvidia-cudnn-download",
    visibility = ["PUBLIC"],
)
