remote_file(
    name = "nvidia-cusparse-download",
    url = "https://files.pythonhosted.org/packages/c2/f5/e1854cb2f2bcd4280c44736c93550cc300ff4b8c95ebe370d0aa7d2b473d/nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
    sha256 = "1ec05d76bbbd8b61b06a80e1eaf8cf4959c3d4ce8e711b65ebd0443bb0ebb13b",
)

prebuilt_python_library(
    name = "nvidia-cusparse",
    binary_src = ":nvidia-cusparse-download",
    visibility = ["PUBLIC"],
)
